### ISSUE TITLE
-v <src>/db:/data/db  Gives odd results

### ISSUE THREAD

**Issue by wls** [dockerfile/mongodb#10]
When I try to mount my host directory as a volume, it doesn't seem to do anything; that's when one gets the not enough space error.

I then tried this `-v <src>/db:/data/db2` to see what would happen, and the `/data/db` directory was blank, but suddenly `/data/db2` had journal files in it... although it didn't attach back to my host.

I then tried `-v <src>/db/:/foo` to see if it was merely globbing the `/data` directory -- now to my surprise the journal files appeared in `/foo`.  That was unexpected, as the documentation seems to imply the MongoDB instance will be looking in /data/db (and whatever was mapped there), rather than where the volume was mounted.

**Comment by johnae** [comment]
Yeah the instructions are actually wrong I'd say. The container defines a mount /data, the instructions talk about mounting something at /data/db. That will give you strange results. What you have to do is this:

mkdir -p /path/on/host/to/data/db ## please note you HAVE to create the db dir inside the data dir, but you don't mount the db dir

docker run -d -p 27017:27017 -v /path/on/host/to/data/dir:/data --name "some-name" dockerfile/mongodb

Hey @pilwon I honestly think this is bad and should be changed since it requires you to create a specifically named directory on the host or have the container crash. Same with the instructions, they shouldn't say what they say because it leads to problems about 70% of the time.

**Comment by johnae** [comment]
@pilwon it seems someone else came to the same conclusion since it's fixed in this fork: https://github.com/kitematic/mongodb/commit/3a3ab3cf4fbcf6b71c9ea534dc375919f2f086d5

**Comment by pilwon** [comment]
@johnae It turns out PR #7 (ce1e3c98060a83cd0a1357340ab53033f92985b7) changed the instruction without Dockerfile being changed.
